### ISSUE TITLE
No database tab in chrome extension.

### ISSUE THREAD

**Issue by shreyasx** [itsgoingd/clockwork#499] opened 2021-05-19 11:22 UTC
Hello,
I do not see the 'database' tab in the clockwork extension in Chrome either. Right now, there's only one tab, called 'Performance'. I think there are supposed to be 4 tabs, 'Performance', 'Models', 'Database' and 'Views'. There any suggestions anyone got for me?

**Comment by itsgoingd** [comment] 2021-05-22 14:25
Hey, the tabs are only shown if they have some content to show. You will only see the database tab on requests which actually make some database queries.

If it still does not show up, make sure you have
- enabled database queries collecting in the Clockwork config (this is enabled by default though)
- set a default database connection in Laravel's database config (should also be set by default)

**Comment by trinketbox** [comment] 2021-06-23 11:20
I occasionally get a database tab and with only 1 query to the sessions table. I've only seen all the tabs once, it's normally just performance. Could you tell us which json files to clean (mentioned in the linked issue) and what that even means (sorry I'm a noob) to get this to work, please?

<img width="1730" alt="Screenshot 2021-06-23 at 12 09 31" src="https://user-images.githubusercontent.com/59660545/123087778-d43ef280-d41c-11eb-8aba-d3bd7733ac8c.png">
<img width="1725" alt="Screenshot 2021-06-23 at 12 08 34" src="https://user-images.githubusercontent.com/59660545/123087789-d6a14c80-d41c-11eb-9bfc-604679ad4b1f.png">

**Comment by itsgoingd** [comment] 2021-06-27 13:00
Hey, you can only see the database tab if we actually collect some database queries. You are inspecting a request for some javascript file on the screenshot, I would assume that produces no database queries.

**Comment by hellomyzn** [comment] 2021-07-16 07:31
Hi, I was able to fixed with `php artisan config:clear`

**Comment by cds** [comment] 2021-07-21 14:14
Try hard refresh browser -> on Crome(MacOS) =  `cmd+shift+r`

**Comment by frankshrestha** [comment] 2022-05-02 11:29
Hi,
Does it capture database queries for Lumen? I see models being retrieved but I don't have the database tab. I have a Vue frontend that calls api built with Lumen v8.3.4. The frontend and backend are two different projects.

`APP_DEBUG` is set to true. Clockwork is registered in `bootstrap/app.php`. `$app->withEloquent()` is enabled.

**Comment by alissaestelle** [comment] 2024-03-05 17:35
I had this same issue, but it turns out I'd just forgotten to run `composer i` in my terminal 😅 I code on a couple different machines and in this case, I installed Clockwork on one machine but forgot to pull it in on the other machine. Easy peasy

**Comment by itsgoingd** [comment] 2024-10-29 01:49
I don't see any issues collecting database queries with Lumen, please provide some reproduction code if this is still an issue.

**Closed by itsgoingd** 2024-10-29 01:49 UTC
