### ISSUE TITLE
Enabled profiler triggers Xdebug on chrome-extension calls

### ISSUE THREAD

**Issue by Defimas** [itsgoingd/clockwork#458] opened 2020-12-11 17:16 UTC
Enabling profiler within the chrome-extension forces Xdebug to trigger profiling (xdebug.start_with_request=trigger) by the extensions own "__clockwork" calls.
Througth its polling behavior cachegrinds start to pile up, which i dont think is intended?

**Comment by itsgoingd** [comment] 2020-12-20 20:31
Hey, this is definitively not intended. We explicitly remove the trigger cookie when doing metadata requests, can you inspect one of the profiles to make sure it's caused by Clockwork?

**Comment by Defimas** [comment] 2020-12-21 14:45
Trigger is present.

![cl](https://user-images.githubusercontent.com/50416302/102788554-14a4b180-43a3-11eb-9aaf-87a1b64eb87d.jpg)

**Comment by itsgoingd** [comment] 2024-11-02 19:47
This should be fixed in Clockwork 5.3 (https://github.com/underground-works/clockwork-app/commit/cda016c0759c160e3981ada44584ebecbb23a84d).

**Closed by itsgoingd** 2024-11-02 19:47 UTC
