### ISSUE TITLE
Undefined method getChanges() Error

### ISSUE THREAD

**Issue by sbahr001** [itsgoingd/clockwork#618] opened 2023-01-04 07:05 UTC
Starting using clockwork to get info on an old project, and I keep getting exceptions. 
```
Call to undefined method PostgresQueryBuilder::getChanges()
```
Which is triggered by the Clockwork middleware.

Updates are still going through, it's just the middleware error out and I have to manually refresh the page to see the changes. 

Environment: PHP 5.6, Laravel 5.2, Postgres is DB. Clockwork - 5.1.12

**Comment by maketvgithub** [comment] 2023-01-07 17:35
@sbahr001 same happened to me. I'm using latest version, but almost similar configuration > PHP 5.6, Laravel 5.4, Clockwork 5.1.4

**Comment by itsgoingd** [comment] 2023-07-01 23:04
Hey, this should be fixed in `dev-master`.

**Comment by isaiahdahl** [comment] 2023-11-13 18:37
I'm still experiencing this with `dev-master` which as far as I can tell installs 5.1.12

php 7.1, laravel 5.4, MySQL 5.6 DB

**Comment by itsgoingd** [comment] 2023-11-13 21:00
Hey, I couldn't reproduce this issue on master, but I've ran into and fixed a different incompatibility with Laravel 5.4.

**Comment by itsgoingd** [comment] 2024-02-21 20:30
Fixed some old Laravel compatibility issues in Clockwork 5.2.

**Closed by itsgoingd** 2024-02-21 20:30 UTC
